# -*- coding: utf-8 -*-
"""Proyek Data Mining_23.61.0258.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNNNLdyErlC30Mc8mLKCN5K4Cl6jDiEM

Link Dataset : https://www.kaggle.com/datasets/adityakadiwal/water-potability

Nama : Surya Farrel Fawwaz Assyarofi

Nim : 23.61.0258

---

##INSTALL & IMPORT
"""

# IMPORT LIBRARY

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# sklearn
from sklearn.model_selection import train_test_split

# IterativeImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# imbalance
from imblearn.over_sampling import SMOTE

# model
from xgboost import XGBClassifier

"""##DATA COLLECTION"""

# load dataset
df = pd.read_csv("/content/drive/MyDrive/PDM 2026/Dataset /water_potability.csv")

# lihat data
df.head()

"""##Exploratory Data Analysis

###Struktur Data & Statistik
"""

df.info()
df.describe()

"""###Missing Value Analysis"""

missing = df.isnull().sum()
print(missing)

plt.figure(figsize=(8,5))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Value Heatmap")
plt.show()

"""###Distribusi Target (Imbalance Check)"""

sns.countplot(x='Potability', data=df)
plt.title("Distribusi Target")
plt.show()

print(df['Potability'].value_counts())
print(df['Potability'].value_counts(normalize=True))

"""###Distribusi Setiap Fitur"""

df.hist(figsize=(12,10), bins=20)
plt.tight_layout()
plt.show()

"""###Korelasi Antar Fitur"""

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""###Boxplot (Deteksi Outlier)"""

plt.figure(figsize=(12,8))
sns.boxplot(data=df)
plt.xticks(rotation=90)
plt.title("Outlier Detection")
plt.show()

"""###Hubungan Fitur dengan Target"""

for col in df.columns[:-1]:
    plt.figure()
    sns.boxplot(x='Potability', y=col, data=df)
    plt.title(f"{col} vs Potability")
    plt.show()

"""###Pairplot"""

sns.pairplot(df.sample(500), hue='Potability')
plt.show()

"""###Skewness (Distribusi Data)"""

print(df.skew())

"""###Outlier check"""

for col in df.columns[:-1]:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(col)
    plt.show()

"""---

##DATA PREPROCESSING

###Pisah fitur & target
"""

X = df.drop("Potability", axis=1)
y = df["Potability"]

"""###Cek Missing Value (Before)

"""

print("=== SEBELUM IMPUTATION ===")
print(df.isnull().sum())

"""###HANDLE MISSING VALUE (Iterative Imputer)"""

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imputer = IterativeImputer(random_state=42)
X = imputer.fit_transform(X)

# balik jadi dataframe
X = pd.DataFrame(X, columns=df.columns[:-1])

"""###Cek Missing Value (After)"""

print("=== SETELAH IMPUTATION ===")
print(X.isnull().sum())

"""###HANDLE IMBALANCE (SMOTE)"""

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)

"""###SPLIT DATA"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""###SCALING"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""##MODELING (XGBoost)"""

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

# Assuming best_xgb_model and best_rf_model are available from previous tuning steps.
# If not, you might need to re-run the tuning for these models.

# 1. Definisikan Base Estimators (Model Dasar)
# Menggunakan model terbaik yang telah dituning sebelumnya
# Memastikan best_xgb_model dan best_rf_model sudah ada dari eksekusi sebelumnya

# Placeholder check - you might need to ensure these variables exist
# For the purpose of this response, I'm assuming 'best_xgb_model' and 'best_rf_model' exist in the kernel state

# If best_xgb_model is not defined, use a default tuned version or the previously defined xgb_model_tuned
if 'best_xgb_model' not in locals():
    # Fallback if best_xgb_model was not preserved or defined
    print("Warning: 'best_xgb_model' not found. Using a default tuned XGBoost.")
    best_xgb_model = XGBClassifier(random_state=42)

# If best_rf_model is not defined, use a default tuned version or the previously defined best_rf_model
if 'best_rf_model' not in locals():
    # Fallback if best_rf_model was not preserved or defined
    print("Warning: 'best_rf_model' not found. Using a default tuned RandomForest.")
    best_rf_model = RandomForestClassifier(random_state=42, n_estimators=300, max_depth=20) # Example of a common tuned RF


estimators = [
    ('xgb', best_xgb_model),
    ('rf', best_rf_model),
    ('knn', KNeighborsClassifier())
]

# 2. Definisikan Stacking Classifier dengan Meta-Learner (Logistic Regression)
stack_clf = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(solver='liblinear', random_state=42),
    cv=5,
    n_jobs=-1
)

# 3. Proses Training Model
print("Training StackingClassifier with tuned base estimators...")
stack_clf.fit(X_train, y_train)

# 4. Proses Prediksi (Menggunakan Data Uji)
print("Menggenerasikan prediksi pada data uji...")
y_pred_stack_clf = stack_clf.predict(X_test)

"""##Feature Importance"""

# Feature Importance
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.barh(df.columns[:-1], best_xgb_model.feature_importances_)
plt.title("Feature Importance (Tuned XGBoost)")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.show()

"""##EVALUASI"""

from sklearn.metrics import accuracy_score, classification_report

print("=== StackingClassifier Model Evaluation (with Tuned Base Estimators) ===")
current_accuracy = accuracy_score(y_test, y_pred_stack_clf)
print(f"Accuracy: {current_accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_stack_clf))

# Now, let's proceed with tuning the final estimator (LogisticRegression) of the StackingClassifier.
# We will use the corrected param_grid_stacking_final that was mentioned in the context.

from sklearn.model_selection import GridSearchCV

# Define the parameter grid for the final_estimator (LogisticRegression)
# Using the corrected param_grid_stacking_final
param_grid_stacking_final = [
    {
        'final_estimator__C': [1, 10], # Reduced values for faster tuning
        'final_estimator__solver': ['liblinear'],
        'final_estimator__penalty': ['l1', 'l2']
    },
    {
        'final_estimator__C': [1, 10], # Reduced values for faster tuning
        'final_estimator__solver': ['lbfgs'],
        'final_estimator__penalty': ['l2'] # lbfgs only supports l2 penalty
    }
]

# Initialize GridSearchCV
grid_search_stacking_final = GridSearchCV(
    stack_clf, # Use the current stack_clf with tuned base estimators
    param_grid=param_grid_stacking_final,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

print("\nStarting GridSearchCV for StackingClassifier's final_estimator...")
grid_search_stacking_final.fit(X_train, y_train)

# Get the best final estimator
best_stack_clf_final = grid_search_stacking_final.best_estimator_

print("Best parameters for StackingClassifier final_estimator:", grid_search_stacking_final.best_params_)

# Make predictions with the best stacking classifier
y_pred_best_stack_tuned_final = best_stack_clf_final.predict(X_test)

# Evaluate the best stacking classifier
print("\n=== Final StackingClassifier Model Evaluation (with Tuned Final Estimator) ===")
final_tuned_accuracy = accuracy_score(y_test, y_pred_best_stack_tuned_final)
print(f"Accuracy: {final_tuned_accuracy}")
print("Classification Report:\n", classification_report(y_test, y_pred_best_stack_tuned_final))

import joblib

# Menyimpan model stacking terbaik hasil tuning ke dalam file biner
joblib.dump(best_stack_clf_final, 'model_stacking_air.pkl')
print("Model 'model_stacking_air.pkl' berhasil disimpan di folder kamu!")

# Simpan scaler bersama model
joblib.dump(scaler, 'scaler_air.pkl')
joblib.dump(best_stack_clf_final, 'model_stacking_air.pkl')

# contoh data yang Potability = 1 (layak minum)
contoh_layak = df[df['Potability'] == 1].dropna().head(5)
print(contoh_layak.to_string())

# SEMUA data yang layak
contoh_layak = df[df['Potability'] == 1].dropna()
print(f"Total data layak: {len(contoh_layak)}")
print(contoh_layak.to_string())